### ISSUE TITLE
File send through a remote share request link is missing

### ISSUE THREAD

**Issue by pjakab** [ErugoOSS/Erugo#149]
When using the link received by email to upload a file. I upload the file - message: upload successful displays -
I then get an email from ERUGO saying that a file was uploaded successfully. When clicking the link provided in the email, I get this error displayed on the web page that opens: "The share you are looking for was not found. You may need to log in to see it."
I log in, and the file is nowhere to be found.

**Comment by DeanWard** [comment]
@pjakab This should be resolved in the latest release, please update your container and give it a try.

**Comment by pjakab** [comment]
Looks good now. Thank you.

I still get the message when pressing the button. I need to log in first, then it works. I just wish that you would add a log-in button after the message so it could be done from the same page.

Thanks.
